version: "3.3"
services:
  mysql:
    image: "mysql:8.0"
    command: "--secure-file-priv=NULL --default-authentication-plugin=mysql_native_password"
    restart: always
    ports:
      - "23306:3306"
    environment:
      MYSQL_DATABASE: "todomvc"
      MYSQL_USER: "todomvc"
      MYSQL_PASSWORD: "todomvc"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - "./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "./volume/mysql/etc/mysql:/etc/mysql"
#      - ./volume/mysql/var/lib/mysql:/var/lib/mysql
#      - ./log/mysql:/var/log/mysql
