CREATE USER IF NOT EXISTS 'todomvc'@'localhost' identified by 'todomvc';
CREATE USER IF NOT EXISTS 'todomvc'@'%' identified by 'todomvc';
CREATE DATABASE IF NOT EXISTS todomvc DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_bin;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, LOCK TABLES ON todomvc.* TO 'todomvc'@'localhost';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, LOCK TABLES ON todomvc.* TO 'todomvc'@'%';

CREATE DATABASE IF NOT EXISTS todomvc_test DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_bin;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, LOCK TABLES ON todomvc_test.* TO 'todomvc'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, LOCK TABLES ON todomvc_test.* TO 'todomvc'@'%';

FLUSH PRIVILEGES;
